//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var string: string { .init(bundle: bundle, preferredLanguages: nil, locale: nil) }
  var color: color { .init(bundle: bundle) }
  var info: info { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }

  func string(bundle: Foundation.Bundle) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: nil)
  }
  func string(locale: Foundation.Locale) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: locale)
  }
  func string(preferredLanguages: [String], locale: Locale? = nil) -> string {
    .init(bundle: bundle, preferredLanguages: preferredLanguages, locale: locale)
  }
  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func info(bundle: Foundation.Bundle) -> info {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func validate() throws {

  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    let bundle: Foundation.Bundle
    let preferredLanguages: [String]?
    let locale: Locale?
    var localizable: localizable { .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale)) }

    func localizable(preferredLanguages: [String]) -> localizable {
      .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale))
    }


    /// This `_R.string.localizable` struct is generated, and contains static references to 25 localization keys.
    struct localizable {
      let source: RswiftResources.StringResource.Source

      /// Value: GithubCopilotLearning
      ///
      /// Key: appName
      var appName: RswiftResources.StringResource { .init(key: "appName", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Bad request
      ///
      /// Key: badRequest
      var badRequest: RswiftResources.StringResource { .init(key: "badRequest", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Please connect to Internet!
      ///
      /// Key: connectToInternet
      var connectToInternet: RswiftResources.StringResource { .init(key: "connectToInternet", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Don't have an account?
      ///
      /// Key: dontHaveAccount
      var dontHaveAccount: RswiftResources.StringResource { .init(key: "dontHaveAccount", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Empty Response
      ///
      /// Key: emptyResponse
      var emptyResponse: RswiftResources.StringResource { .init(key: "emptyResponse", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Oops!
      ///
      /// Key: error
      var error: RswiftResources.StringResource { .init(key: "error", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Image not found
      ///
      /// Key: imageNotFound
      var imageNotFound: RswiftResources.StringResource { .init(key: "imageNotFound", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Internal Server error.
      ///
      /// Key: internalServerError
      var internalServerError: RswiftResources.StringResource { .init(key: "internalServerError", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Internet connection error.
      ///
      /// Key: internetConnectionError
      var internetConnectionError: RswiftResources.StringResource { .init(key: "internetConnectionError", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Invalid response
      ///
      /// Key: invalidResponse
      var invalidResponse: RswiftResources.StringResource { .init(key: "invalidResponse", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Invalid url
      ///
      /// Key: invalidURL
      var invalidURL: RswiftResources.StringResource { .init(key: "invalidURL", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Let's go!
      ///
      /// Key: letsGo
      var letsGo: RswiftResources.StringResource { .init(key: "letsGo", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
      ///
      /// Key: loremIpsumDesc
      var loremIpsumDesc: RswiftResources.StringResource { .init(key: "loremIpsumDesc", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Maximum retry attempts exceed
      ///
      /// Key: maxAttemptsExceeded
      var maxAttemptsExceeded: RswiftResources.StringResource { .init(key: "maxAttemptsExceeded", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Our best services
      ///
      /// Key: ourBestServices
      var ourBestServices: RswiftResources.StringResource { .init(key: "ourBestServices", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Request failed
      ///
      /// Key: requestFailed
      var requestFailed: RswiftResources.StringResource { .init(key: "requestFailed", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Request timeout.
      ///
      /// Key: requestTimeout
      var requestTimeout: RswiftResources.StringResource { .init(key: "requestTimeout", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Result not Found
      ///
      /// Key: resultNotFound
      var resultNotFound: RswiftResources.StringResource { .init(key: "resultNotFound", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Server not Found
      ///
      /// Key: serverNotFound
      var serverNotFound: RswiftResources.StringResource { .init(key: "serverNotFound", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Signup
      ///
      /// Key: signup
      var signup: RswiftResources.StringResource { .init(key: "signup", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Something went wrong. Please try again.
      ///
      /// Key: somethingWentWrong
      var somethingWentWrong: RswiftResources.StringResource { .init(key: "somethingWentWrong", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: This is test snackbar
      ///
      /// Key: testSnackBar
      var testSnackBar: RswiftResources.StringResource { .init(key: "testSnackBar", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Unable to create file
      ///
      /// Key: unableToCreate
      var unableToCreate: RswiftResources.StringResource { .init(key: "unableToCreate", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Unauthorised User.
      ///
      /// Key: unauthorisedUser
      var unauthorisedUser: RswiftResources.StringResource { .init(key: "unauthorisedUser", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Url not found
      ///
      /// Key: urlNotFound
      var urlNotFound: RswiftResources.StringResource { .init(key: "urlNotFound", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }
    }
  }

  /// This `_R.color` struct is generated, and contains static references to 5 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }

    /// Color `ShimmerBG`.
    var shimmerBG: RswiftResources.ColorResource { .init(name: "ShimmerBG", path: [], bundle: bundle) }

    /// Color `ShimmerWave`.
    var shimmerWave: RswiftResources.ColorResource { .init(name: "ShimmerWave", path: [], bundle: bundle) }

    /// Color `ThemeColor`.
    var themeColor: RswiftResources.ColorResource { .init(name: "ThemeColor", path: [], bundle: bundle) }

    /// Color `snackBarBackground`.
    var snackBarBackground: RswiftResources.ColorResource { .init(name: "snackBarBackground", path: [], bundle: bundle) }
  }

  /// This `_R.info` struct is generated, and contains static references to 1 properties.
  struct info {
    let bundle: Foundation.Bundle
    var uiApplicationSceneManifest: uiApplicationSceneManifest { .init(bundle: bundle) }

    func uiApplicationSceneManifest(bundle: Foundation.Bundle) -> uiApplicationSceneManifest {
      .init(bundle: bundle)
    }

    struct uiApplicationSceneManifest {
      let bundle: Foundation.Bundle

      let uiApplicationSupportsMultipleScenes: Bool = true

      var _key: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest"], key: "_key") ?? "UIApplicationSceneManifest" }
    }
  }

  /// This `_R.file` struct is generated, and contains static references to 2 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `Tests.plist`.
    var testsPlist: RswiftResources.FileResource { .init(name: "Tests", pathExtension: "plist", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `UITests.plist`.
    var uiTestsPlist: RswiftResources.FileResource { .init(name: "UITests", pathExtension: "plist", bundle: bundle, locale: LocaleReference.none) }
  }
}